interface SimulationBannerProps {
  active: boolean;
}

export function SimulationBanner({ active }: SimulationBannerProps) {
  if (!active) return null;

  return (
    <div className="simulation-banner flex items-center justify-center gap-3 px-4 py-2">
      <span className="relative flex h-2.5 w-2.5">
        <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-amber-400 opacity-75" />
        <span className="relative inline-flex h-2.5 w-2.5 rounded-full bg-amber-400" />
      </span>
      <span className="font-mono text-xs font-semibold tracking-[0.2em] text-amber-300 uppercase">
        Simulation Mode
      </span>
      <span className="hidden text-xs text-amber-200/60 sm:inline">
        — Data generated by simulated Wi-Fi sensor. Not from physical hardware.
      </span>
    </div>
  );
}
